### ISSUE TITLE
Cannot paginate search results.

### ISSUE THREAD

**Issue by jamesbrauman** [TomLingham/Laravel-Searchy#5]
Hi,

When calling ->paginate() on the query builder returned by the Searchy package, it is throwing an SQL error.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relevance' in 'having clause' (SQL: select count(*) as aggregate from `burial_records` having `relevance` > 0) 
```

Thanks

**Comment by Rtransat** [comment]
Hi,

Sorry to reopen this issue. The pagination is still not supported ? Btw, the relationships are supported ?

Thx

**Comment by TomLingham** [comment]
@Rtransat, that is ok. Sorry for not replying sooner. You can use pagination by returning the Database Query Object instead of an array of results. Take a look at the readme under "Usage" (You want to use `getQuery()` instead of `get()`). http://laravel.com/docs/master/pagination

Relationships aren't supported. If you are doing complex searches, across tables then there are more robust solutions out there. Searchy is simple by design :smile:

I hope that helps!
