### ISSUE TITLE
Searching joined/concatenated columns fails when a field is null

### ISSUE THREAD

**Issue by rainerkent** [TomLingham/Laravel-Searchy#90]
I have this code
``` php
$matchedProfiles = Searchy::profiles('first_name::middle_name::last_name')
                            ->query($name)->get();
```
The `middle_name` column is nullable.

It only returns the matched records where `middle_name` is not null. 

I am omitting the `middle_name` column in fields for now. Is there any workaround for this?

**Comment by syscoch** [comment]
Hello,
we had the same issue. We adapted the library by using CONCAT_WS instead of CONCAT

Before :
$query[] = $this->buildSelectCriteria("CONCAT({$concatString})");

After:
$query[] = $this->buildSelectCriteria("**CONCAT_WS**('',{$concatString})");

In laravel, it's in file BaseSearchDriver.php

I know it's late but maybe it helps someone.

Have a great day.

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
